project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



